// apps/web/app/pages/library/index.vue
<script setup lang="ts">
definePageMeta({ middleware: "auth" });

const PAGE_SIZE = 25;
const DEBOUNCE_MS = 400;

const route = useRoute();

const filters = computed(() => {
  const q = route.query;
  const page = Number.parseInt(firstParam(q.page) || "1", 10);
  return {
    document_type: firstParam(q.document_type),
    correspondent: firstParam(q.correspondent),
    date_from: firstParam(q.date_from),
    date_to: firstParam(q.date_to),
    text: firstParam(q.text),
    ordering: firstParam(q.ordering) || DEFAULT_ORDERING,
    tags: allParams(q.tags),
    page: Number.isFinite(page) && page > 0 ? page : 1,
  };
});

const tab = computed(() => (firstParam(route.query.tab) === "review" ? "review" : "archive"));

const query = computed<LibraryQuery>(() => ({
  document_type: filters.value.document_type || null,
  correspondent: filters.value.correspondent || null,
  date_from: filters.value.date_from || null,
  date_to: filters.value.date_to || null,
  text: filters.value.text || null,
  tags: filters.value.tags.length > 0 ? filters.value.tags : null,
  ordering: filters.value.ordering,
  page: filters.value.page,
  page_size: PAGE_SIZE,
}));

const library = useLibrary(query);
const facet = useTagFacet();

const text = ref("");
const correspondent = ref("");
const filtersOpen = ref(false);
let debounceHandle: ReturnType<typeof setTimeout> | null = null;

watch(
  filters,
  (next) => {
    text.value = next.text;
    correspondent.value = next.correspondent;
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  if (debounceHandle !== null) clearTimeout(debounceHandle);
});

const rows = computed<readonly LibraryItem[]>(() => library.data.value?.results ?? []);
const total = computed(() => library.data.value?.total ?? 0);
const pages = computed(() => totalPages(total.value, PAGE_SIZE));
const errorText = computed(() =>
  library.isError.value ? detailFrom(library.error.value, "Laden fehlgeschlagen.") : null,
);
const hasActiveFilters = computed(() => {
  const f = filters.value;
  return Boolean(f.document_type || f.correspondent || f.date_from || f.date_to || f.text) || f.tags.length > 0;
});

function userTags(item: LibraryItem): string[] {
  return sortTagsImportantFirst(userFacingTags(item.tags));
}

function syncUrl(patch: Record<string, unknown>): void {
  void navigateTo({ path: "/library", query: cleanLibraryQuery({ ...filters.value, ...patch }) });
}

function onFilterChange(patch: Record<string, unknown>): void {
  syncUrl({ ...patch, page: 1 });
}

function onTextInput(): void {
  if (debounceHandle !== null) clearTimeout(debounceHandle);
  debounceHandle = setTimeout(() => {
    debounceHandle = null;
    syncUrl({ text: text.value, page: 1 });
  }, DEBOUNCE_MS);
}

function toggleTag(name: string): void {
  const current = filters.value.tags;
  const next = current.includes(name) ? current.filter((t) => t !== name) : [...current, name];
  syncUrl({ tags: next, page: 1 });
}

function switchTab(next: "archive" | "review"): void {
  void navigateTo({ path: "/library", query: next === "review" ? { tab: "review" } : {} });
}

function clearFilters(): void {
  void navigateTo({ path: "/library", query: {} });
}

function goToPage(next: number): void {
  if (next < 1 || next > pages.value) return;
  syncUrl({ page: next });
}

function valueOf(event: Event): string {
  return (event.target as HTMLInputElement | HTMLSelectElement).value;
}
</script>

<template>
  <div class="flex min-h-full flex-col">
    <div class="flex-1 px-4 py-8 sm:px-6">
      <div class="mx-auto max-w-6xl">
        <div class="flex items-center gap-2 border-b border-hairline">
          <button
            v-for="t in (['archive', 'review'] as const)"
            :key="t"
            type="button"
            :data-testid="`tab-${t}`"
            class="-mb-px border-b-2 px-3 py-2 text-sm font-medium"
            :class="tab === t ? 'border-ink text-ink' : 'border-transparent text-ink-muted'"
            @click="switchTab(t)"
          >
            {{ t === "archive" ? "Archiv" : "Zur Prüfung" }}
          </button>
        </div>

        <LibraryReviewTab v-if="tab === 'review'" />
        <template v-else>
          <div class="mt-4 flex items-baseline justify-between gap-4">
            <h1 class="text-lg font-semibold tracking-tight text-ink">Bibliothek</h1>
            <p class="text-xs text-ink-subtle" data-testid="library-total">{{ total }} Dokument(e)</p>
          </div>

          <button
            type="button"
            class="mt-4 w-full rounded-lg border border-hairline px-3 py-2 text-xs font-medium text-ink md:hidden"
            @click="filtersOpen = !filtersOpen"
          >
            Filter &amp; Tags {{ filtersOpen ? "ausblenden" : "anzeigen" }}
          </button>

          <div class="mt-4 grid gap-6 md:grid-cols-[16rem_1fr]">
            <aside class="flex-col gap-4 md:flex" :class="filtersOpen ? 'flex' : 'hidden'">
              <label class="block text-xs font-medium text-ink-muted">
                Suche
                <input
                  v-model="text"
                  type="search"
                  name="text"
                  placeholder="Volltext…"
                  class="mt-1 w-full rounded-lg border border-hairline bg-surface px-3 py-2 text-sm text-ink focus:border-accent focus:outline-none"
                  @input="onTextInput"
                >
              </label>

              <label class="block text-xs font-medium text-ink-muted">
                Dokumenttyp
                <select
                  name="document_type"
                  :value="filters.document_type"
                  class="mt-1 w-full rounded-lg border border-hairline bg-surface px-3 py-2 text-sm text-ink"
                  @change="onFilterChange({ document_type: valueOf($event) })"
                >
                  <option value="">Alle</option>
                  <option v-for="dt in DOC_TYPES" :key="dt" :value="dt">{{ dt }}</option>
                </select>
              </label>

              <label class="block text-xs font-medium text-ink-muted">
                Korrespondent
                <input
                  v-model="correspondent"
                  type="text"
                  name="correspondent"
                  class="mt-1 w-full rounded-lg border border-hairline bg-surface px-3 py-2 text-sm text-ink"
                  @blur="onFilterChange({ correspondent })"
                >
              </label>

              <div class="grid grid-cols-2 gap-2">
                <label class="block text-xs font-medium text-ink-muted">
                  Von
                  <input
                    type="date"
                    name="date_from"
                    :value="filters.date_from"
                    class="mt-1 w-full rounded-lg border border-hairline bg-surface px-2 py-2 text-sm text-ink"
                    @change="onFilterChange({ date_from: valueOf($event) })"
                  >
                </label>
                <label class="block text-xs font-medium text-ink-muted">
                  Bis
                  <input
                    type="date"
                    name="date_to"
                    :value="filters.date_to"
                    class="mt-1 w-full rounded-lg border border-hairline bg-surface px-2 py-2 text-sm text-ink"
                    @change="onFilterChange({ date_to: valueOf($event) })"
                  >
                </label>
              </div>

              <label class="block text-xs font-medium text-ink-muted">
                Sortierung
                <select
                  name="ordering"
                  :value="filters.ordering"
                  class="mt-1 w-full rounded-lg border border-hairline bg-surface px-3 py-2 text-sm text-ink"
                  @change="onFilterChange({ ordering: valueOf($event) })"
                >
                  <option v-for="opt in ORDERING_OPTIONS" :key="opt.value" :value="opt.value">{{ opt.label }}</option>
                </select>
              </label>

              <div v-if="facet.data.value?.results?.length">
                <p class="text-xs font-medium text-ink-muted">Tags</p>
                <div class="mt-2 flex flex-wrap gap-1.5">
                  <button
                    v-for="tag in facet.data.value.results"
                    :key="tag.name"
                    type="button"
                    class="rounded-full border px-2.5 py-1 text-[11px] font-medium"
                    :class="filters.tags.includes(tag.name) ? 'border-accent text-accent' : 'border-hairline text-ink-muted'"
                    @click="toggleTag(tag.name)"
                  >
                    {{ tag.name }} ({{ tag.count }})
                  </button>
                </div>
              </div>

              <button
                v-if="hasActiveFilters"
                type="button"
                class="rounded-lg border border-hairline px-3 py-1.5 text-xs font-medium text-ink hover:bg-canvas"
                @click="clearFilters"
              >
                Filter zurücksetzen
              </button>
            </aside>

            <section>
              <p v-if="errorText" class="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
                {{ errorText }}
              </p>
              <p v-else-if="library.isPending.value" class="text-xs text-ink-subtle">Lade Dokumente…</p>
              <p
                v-else-if="rows.length === 0"
                class="rounded-lg border border-hairline bg-surface px-4 py-8 text-center text-sm text-ink-muted"
              >
                Keine Dokumente gefunden.
              </p>
              <template v-else>
                <div class="hidden overflow-x-auto rounded-lg border border-hairline md:block">
                  <table class="w-full text-sm">
                    <thead class="bg-canvas text-left text-xs text-ink-muted">
                      <tr>
                        <th class="px-3 py-2 font-medium">Titel</th>
                        <th class="px-3 py-2 font-medium">Typ</th>
                        <th class="px-3 py-2 font-medium">Korrespondent</th>
                        <th class="px-3 py-2 font-medium">Datum</th>
                        <th class="px-3 py-2 font-medium">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr v-for="row in rows" :key="row.id" class="border-t border-hairline hover:bg-canvas/50">
                        <td class="px-3 py-2">
                          <NuxtLink :to="`/library/${row.id}`" class="text-ink hover:text-accent">{{ row.title }}</NuxtLink>
                          <div v-if="userTags(row).length" class="mt-1 flex flex-wrap gap-1">
                            <span
                              v-for="tag in userTags(row)"
                              :key="tag"
                              class="rounded-full px-2 py-0.5 text-[10px] font-medium"
                              :class="tag === 'wichtig' ? 'bg-amber-100 text-amber-800' : 'bg-surface-raised text-ink-muted'"
                            >
                              {{ tag === "wichtig" ? "★ wichtig" : tag }}
                            </span>
                          </div>
                        </td>
                        <td class="px-3 py-2 text-ink-muted">{{ row.document_type ?? "—" }}</td>
                        <td class="px-3 py-2 text-ink-muted">{{ row.correspondent ?? "—" }}</td>
                        <td class="px-3 py-2 text-ink-muted">{{ row.created ?? "—" }}</td>
                        <td class="px-3 py-2">
                          <ProcessingBadge
                            :tags="row.lifecycle_tags"
                            :error-message="row.ai_error_message"
                            :in-flight="row.is_processing"
                          />
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>

                <ul class="flex flex-col gap-2 md:hidden">
                  <li v-for="row in rows" :key="row.id" class="rounded-lg border border-hairline bg-surface p-3">
                    <NuxtLink :to="`/library/${row.id}`" class="text-sm font-medium text-ink">{{ row.title }}</NuxtLink>
                    <p class="mt-1 text-xs text-ink-muted">{{ row.document_type ?? "—" }} · {{ row.correspondent ?? "—" }}</p>
                    <p class="mt-0.5 text-xs text-ink-subtle">{{ row.created ?? "—" }}</p>
                    <div class="mt-2">
                      <ProcessingBadge
                        :tags="row.lifecycle_tags"
                        :error-message="row.ai_error_message"
                        :in-flight="row.is_processing"
                      />
                    </div>
                  </li>
                </ul>

                <div v-if="pages > 1" class="mt-4 flex items-center justify-between gap-3">
                  <button
                    type="button"
                    :disabled="filters.page <= 1"
                    class="rounded-lg border border-hairline px-3 py-1.5 text-xs font-medium text-ink disabled:opacity-50"
                    @click="goToPage(filters.page - 1)"
                  >
                    Zurück
                  </button>
                  <span class="text-xs text-ink-subtle">Seite {{ filters.page }} von {{ pages }}</span>
                  <button
                    type="button"
                    :disabled="filters.page >= pages"
                    data-testid="next-page"
                    class="rounded-lg border border-hairline px-3 py-1.5 text-xs font-medium text-ink disabled:opacity-50"
                    @click="goToPage(filters.page + 1)"
                  >
                    Weiter
                  </button>
                </div>
              </template>
            </section>
          </div>
        </template>
      </div>
    </div>
  </div>
</template>

// apps/web/src/routes/Library.tsx
import { Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";

import { Nav } from "../components/Nav";
import { ProcessingBadge } from "../components/ProcessingBadge";
import type { LibraryItem, LibraryQuery, TagFacet } from "../lib/library";
import { DOC_TYPES, useLibrary, useTagFacet } from "../lib/library";
import {
  isInFlight,
  useBulkReprocess,
  useProcessingState,
} from "../lib/documents";
import type { InboxItem } from "../lib/inbox";
import { useBulkApprove, useInboxList } from "../lib/inbox";

const DEFAULT_PAGE_SIZE = 25;

type Search = {
  tab?: "review" | "archive";
  document_type?: string;
  correspondent?: string;
  date_from?: string;
  date_to?: string;
  text?: string;
  tags?: string[];
  page?: number;
};

type LocalForm = {
  document_type: string;
  correspondent: string;
  date_from: string;
  date_to: string;
  text: string;
};

function searchToForm(s: Search): LocalForm {
  return {
    document_type: s.document_type ?? "",
    correspondent: s.correspondent ?? "",
    date_from: s.date_from ?? "",
    date_to: s.date_to ?? "",
    text: s.text ?? "",
  };
}

function formToSearch(
  f: LocalForm,
  page: number,
  tags: string[] | undefined,
): Search {
  const out: Search = {};
  if (f.document_type) out.document_type = f.document_type;
  if (f.correspondent) out.correspondent = f.correspondent;
  if (f.date_from) out.date_from = f.date_from;
  if (f.date_to) out.date_to = f.date_to;
  if (f.text) out.text = f.text;
  if (tags && tags.length > 0) out.tags = tags;
  if (page > 1) out.page = page;
  return out;
}

export function Library({ search }: { search: Search }) {
  const navigate = useNavigate();
  const [form, setForm] = useState<LocalForm>(() => searchToForm(search));
  const facet = useTagFacet();

  const lastSearchRef = useRef(search);
  useEffect(() => {
    if (JSON.stringify(lastSearchRef.current) !== JSON.stringify(search)) {
      lastSearchRef.current = search;
      setForm(searchToForm(search));
    }
  }, [search]);

  useEffect(() => {
    const timer = setTimeout(() => {
      const next = formToSearch(form, 1, search.tags);
      if (search.tab) next.tab = search.tab;
      const current = { ...search };
      delete current.page;
      if (JSON.stringify(next) !== JSON.stringify(current)) {
        void navigate({ to: "/library", search: next });
      }
    }, 400);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form]);

  const query = useMemo<LibraryQuery>(
    () => ({
      ...search,
      page: search.page ?? 1,
      page_size: DEFAULT_PAGE_SIZE,
      ordering: "-created",
    }),
    [search],
  );
  const list = useLibrary(query);
  const processing = useProcessingState();

  const onResetFilters = () => {
    setForm(searchToForm({}));
    void navigate({ to: "/library", search: search.tab ? { tab: search.tab } : {} });
  };

  const goToPage = (page: number) => {
    void navigate({
      to: "/library",
      search: { ...search, page: page > 1 ? page : undefined },
    });
  };

  const toggleTag = (tag: string) => {
    const current = search.tags ?? [];
    const next = current.includes(tag)
      ? current.filter((t) => t !== tag)
      : [...current, tag];
    void navigate({
      to: "/library",
      search: {
        ...search,
        tags: next.length > 0 ? next : undefined,
        page: undefined,
      },
    });
  };

  const total = list.data?.total ?? 0;
  const lastPage = Math.max(1, Math.ceil(total / DEFAULT_PAGE_SIZE));
  const currentPage = search.page ?? 1;
  const errorDetail = list.error?.response?.data?.detail ?? list.error?.message;

  const tab = search.tab ?? "archive";

  // ----- Bulk reprocess (archive tab only) -----
  const bulkReprocess = useBulkReprocess();
  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [bulkResult, setBulkResult] = useState<{
    succeeded: number;
    failed: number;
  } | null>(null);

  const visibleIds = useMemo(
    () => list.data?.results.map((r) => r.id) ?? [],
    [list.data],
  );

  const effectiveSelected = useMemo(() => {
    if (!visibleIds.length) return selected;
    const visible = new Set(visibleIds);
    let pruned = false;
    const next = new Set<number>();
    selected.forEach((id) => {
      if (visible.has(id)) next.add(id);
      else pruned = true;
    });
    return pruned ? next : selected;
  }, [selected, visibleIds]);

  const selectedCount = effectiveSelected.size;
  const allSelected =
    visibleIds.length > 0 && visibleIds.every((id) => effectiveSelected.has(id));

  const toggleOne = (id: number) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const toggleAll = () => {
    if (allSelected) setSelected(new Set());
    else setSelected(new Set(visibleIds));
  };

  const onBulkReprocess = async () => {
    const ids = Array.from(effectiveSelected);
    if (ids.length === 0) return;
    setBulkResult(null);
    const res = await bulkReprocess.mutateAsync(ids);
    setBulkResult({ succeeded: res.succeeded.length, failed: res.failed.length });
    setSelected((prev) => {
      const next = new Set(prev);
      res.succeeded.forEach((id) => next.delete(id));
      return next;
    });
  };

  const tabCls = (t: "review" | "archive") =>
    `px-4 py-2.5 text-sm font-medium border-b-2 transition-colors ${
      tab === t
        ? "border-ink text-ink"
        : "border-transparent text-ink-muted hover:text-ink"
    }`;

  return (
    <div className="flex min-h-full flex-col">
      <Nav active="library" />

      {/* Tabs */}
      <div className="border-b border-hairline bg-canvas px-6">
        <nav className="flex gap-1">
          <button
            onClick={() => navigate({ to: "/library", search: { tab: "review" } })}
            className={tabCls("review")}
          >
            Zur Prüfung
          </button>
          <button
            onClick={() =>
              navigate({
                to: "/library",
                search: (prev) => ({ ...prev, tab: "archive" }),
              })
            }
            className={tabCls("archive")}
          >
            Archiv
          </button>
        </nav>
      </div>

      {tab === "review" ? (
        <ZurPruefungTab />
      ) : (
        <main className="mx-auto flex w-full max-w-7xl flex-1 gap-6 px-6 py-6">
          {/* Filter sidebar */}
          <aside className="w-60 shrink-0">
            <div className="rounded-lg border border-hairline bg-surface p-4">
              <h2 className="text-xs font-semibold uppercase tracking-wide text-ink-subtle">
                Filter
              </h2>
              <div className="mt-3 space-y-3">
                <Field label="Dokumenttyp">
                  <select
                    value={form.document_type}
                    onChange={(e) =>
                      setForm({ ...form, document_type: e.target.value })
                    }
                    className={inputCls}
                  >
                    <option value="">Alle</option>
                    {DOC_TYPES.map((t) => (
                      <option key={t} value={t}>
                        {t}
                      </option>
                    ))}
                  </select>
                </Field>
                <Field label="Korrespondent">
                  <input
                    type="text"
                    value={form.correspondent}
                    onChange={(e) =>
                      setForm({ ...form, correspondent: e.target.value })
                    }
                    placeholder="Name eingeben"
                    className={inputCls}
                  />
                </Field>
                <div className="grid grid-cols-2 gap-2">
                  <Field label="Von">
                    <input
                      type="date"
                      value={form.date_from}
                      onChange={(e) =>
                        setForm({ ...form, date_from: e.target.value })
                      }
                      className={inputCls}
                    />
                  </Field>
                  <Field label="Bis">
                    <input
                      type="date"
                      value={form.date_to}
                      onChange={(e) =>
                        setForm({ ...form, date_to: e.target.value })
                      }
                      className={inputCls}
                    />
                  </Field>
                </div>
                <Field label="Stichwort">
                  <input
                    type="text"
                    value={form.text}
                    onChange={(e) => setForm({ ...form, text: e.target.value })}
                    placeholder="Volltextsuche"
                    className={inputCls}
                  />
                </Field>
                <button
                  type="button"
                  onClick={onResetFilters}
                  className="mt-1 w-full rounded-md border border-hairline bg-canvas px-3 py-1.5 text-xs font-medium text-ink-muted hover:bg-surface-raised"
                >
                  Filter zurücksetzen
                </button>
              </div>
            </div>

            <TagFacetPanel
              facet={facet.data?.results}
              isLoading={facet.isLoading}
              selected={search.tags ?? []}
              onToggle={toggleTag}
            />
          </aside>

          <section className="min-w-0 flex-1">
            <div className="flex items-baseline justify-between">
              <h1 className="text-lg font-semibold tracking-tight text-ink">
                Bibliothek
              </h1>
              <span className="text-sm text-ink-subtle">
                {list.isLoading ? "…" : `${total} Dokumente`}
              </span>
            </div>

            {(search.tags ?? []).length > 0 && (
              <div className="mt-3 flex flex-wrap items-center gap-2">
                <span className="text-xs font-medium uppercase tracking-wide text-ink-subtle">
                  Aktive Tags
                </span>
                {(search.tags ?? []).map((tag) => (
                  <button
                    key={tag}
                    type="button"
                    onClick={() => toggleTag(tag)}
                    className="inline-flex items-center gap-1 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-0.5 text-xs text-emerald-800 hover:bg-emerald-100"
                    title="Tag entfernen"
                  >
                    {tag}
                    <span aria-hidden className="text-emerald-500">×</span>
                  </button>
                ))}
              </div>
            )}

            {errorDetail && (
              <p className="mt-3 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
                {errorDetail}
              </p>
            )}

            {list.data && list.data.results.length === 0 && !list.isLoading && (
              <div className="mt-6 rounded-lg border border-dashed border-hairline bg-surface p-8 text-center text-sm text-ink-subtle">
                Keine Treffer für diese Filter.
              </div>
            )}

            {list.data && list.data.results.length > 0 && (
              <>
                {selectedCount > 0 && (
                  <div className="sticky top-0 z-10 mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-inverse/20 bg-inverse px-4 py-2 text-sm text-on-inverse">
                    <span>
                      {selectedCount}{" "}
                      {selectedCount === 1
                        ? "Dokument ausgewählt"
                        : "Dokumente ausgewählt"}
                    </span>
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={() => setSelected(new Set())}
                        disabled={bulkReprocess.isPending}
                        className="rounded-md border border-white/20 px-3 py-1 text-xs text-on-inverse/80 hover:bg-white/10 disabled:opacity-60"
                      >
                        Auswahl aufheben
                      </button>
                      <button
                        type="button"
                        onClick={onBulkReprocess}
                        disabled={bulkReprocess.isPending}
                        className="rounded-md bg-surface px-3 py-1 text-xs font-medium text-ink hover:bg-canvas disabled:opacity-60"
                      >
                        {bulkReprocess.isPending
                          ? "Stoße neu an…"
                          : `${selectedCount} erneut verarbeiten`}
                      </button>
                    </div>
                  </div>
                )}

                {bulkResult && (
                  <p
                    className={`mt-3 rounded-lg border px-3 py-2 text-sm ${
                      bulkResult.failed
                        ? "border-amber-200 bg-amber-50 text-amber-800"
                        : "border-emerald-200 bg-emerald-50 text-emerald-800"
                    }`}
                  >
                    {bulkResult.succeeded} neu angestoßen
                    {bulkResult.failed
                      ? ` · ${bulkResult.failed} fehlgeschlagen`
                      : ""}
                    .
                  </p>
                )}

                <div className="mt-4 rounded-lg border border-hairline bg-surface">
                  <table className="w-full text-left text-sm">
                    <thead className="border-b border-hairline text-xs uppercase tracking-wide text-ink-subtle">
                      <tr>
                        <th className="w-8 px-3 py-2.5">
                          <input
                            type="checkbox"
                            aria-label="Alle auswählen"
                            checked={allSelected}
                            onChange={toggleAll}
                            className="h-4 w-4 cursor-pointer accent-ink"
                          />
                        </th>
                        <th className="px-3 py-2.5">Titel</th>
                        <th className="px-3 py-2.5">Typ</th>
                        <th className="px-3 py-2.5">Korrespondent</th>
                        <th className="px-3 py-2.5">Datum</th>
                        <th className="px-3 py-2.5">Status</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-hairline-soft">
                      {list.data.results.map((row) => (
                        <Row
                          key={row.id}
                          row={row}
                          selectedTags={search.tags ?? []}
                          onTagClick={toggleTag}
                          checked={effectiveSelected.has(row.id)}
                          onToggle={() => toggleOne(row.id)}
                          inFlight={isInFlight(row.id, processing.data)}
                          onClick={() =>
                            navigate({
                              to: "/library/$id",
                              params: { id: String(row.id) },
                            })
                          }
                        />
                      ))}
                    </tbody>
                  </table>
                </div>
              </>
            )}

            {lastPage > 1 && (
              <div className="mt-4 flex items-center justify-end gap-2 text-sm">
                <button
                  type="button"
                  onClick={() => goToPage(currentPage - 1)}
                  disabled={currentPage <= 1}
                  className="rounded-md border border-hairline bg-surface px-3 py-1.5 text-xs text-ink-muted hover:bg-canvas disabled:opacity-50"
                >
                  ← Zurück
                </button>
                <span className="text-xs text-ink-subtle">
                  Seite {currentPage} / {lastPage}
                </span>
                <button
                  type="button"
                  onClick={() => goToPage(currentPage + 1)}
                  disabled={currentPage >= lastPage}
                  className="rounded-md border border-hairline bg-surface px-3 py-1.5 text-xs text-ink-muted hover:bg-canvas disabled:opacity-50"
                >
                  Weiter →
                </button>
              </div>
            )}
          </section>
        </main>
      )}
    </div>
  );
}

function TagFacetPanel({
  facet,
  isLoading,
  selected,
  onToggle,
}: {
  facet: TagFacet[] | undefined;
  isLoading: boolean;
  selected: string[];
  onToggle: (tag: string) => void;
}) {
  return (
    <div className="mt-4 rounded-lg border border-hairline bg-surface p-4">
      <h2 className="text-xs font-semibold uppercase tracking-wide text-ink-subtle">
        Tags
      </h2>
      {isLoading && (
        <p className="mt-2 text-xs text-ink-subtle">Lade Tags…</p>
      )}
      {!isLoading && facet && facet.length === 0 && (
        <p className="mt-2 text-xs text-ink-subtle">
          Noch keine Tags mit ≥2 Dokumenten.
        </p>
      )}
      {facet && facet.length > 0 && (
        <div className="mt-3 flex flex-wrap gap-1.5">
          {facet.map((t) => {
            const active = selected.includes(t.name);
            return (
              <button
                key={t.name}
                type="button"
                onClick={() => onToggle(t.name)}
                className={
                  active
                    ? "inline-flex items-center gap-1 rounded-full border border-emerald-300 bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-800"
                    : "inline-flex items-center gap-1 rounded-full border border-hairline bg-canvas px-2.5 py-1 text-xs text-ink-muted hover:border-hairline-soft hover:bg-surface-raised"
                }
                title={
                  active
                    ? `Tag '${t.name}' aktiv — klicken zum Entfernen`
                    : `Tag '${t.name}' anwenden`
                }
              >
                <span>{t.name}</span>
                <span className={active ? "text-emerald-600" : "text-ink-faint"}>
                  {t.count}
                </span>
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
}

function Row({
  row,
  selectedTags,
  onTagClick,
  checked,
  onToggle,
  inFlight,
  onClick,
}: {
  row: LibraryItem;
  selectedTags: string[];
  onTagClick: (tag: string) => void;
  checked: boolean;
  onToggle: () => void;
  inFlight: boolean;
  onClick: () => void;
}) {
  return (
    <tr className="hover:bg-canvas">
      <td className="w-8 px-3 py-2.5" onClick={(e) => e.stopPropagation()}>
        <input
          type="checkbox"
          aria-label={`${row.title} auswählen`}
          checked={checked}
          onChange={onToggle}
          className="h-4 w-4 cursor-pointer accent-ink"
        />
      </td>
      <td onClick={onClick} className="cursor-pointer px-3 py-2.5">
        <div className="font-medium text-ink">{row.title}</div>
        {row.original_file_name && row.original_file_name !== row.title && (
          <div className="text-[10px] text-ink-faint">
            Original: {row.original_file_name}
          </div>
        )}
        {row.tags.length > 0 && (
          <div className="mt-1 flex flex-wrap gap-1">
            {row.tags.slice(0, 5).map((t) => {
              const active = selectedTags.includes(t);
              return (
                <button
                  key={t}
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    onTagClick(t);
                  }}
                  className={
                    active
                      ? "rounded-full border border-emerald-300 bg-emerald-50 px-2 py-0.5 text-[10px] text-emerald-800"
                      : "rounded-full border border-hairline bg-canvas px-2 py-0.5 text-[10px] text-ink-muted hover:bg-surface-raised"
                  }
                  title={`Auf Tag '${t}' filtern`}
                >
                  {t}
                </button>
              );
            })}
          </div>
        )}
      </td>
      <td onClick={onClick} className="cursor-pointer px-3 py-2.5 text-ink-muted">
        {row.document_type ?? "—"}
      </td>
      <td onClick={onClick} className="cursor-pointer px-3 py-2.5 text-ink-muted">
        {row.correspondent ?? "—"}
      </td>
      <td onClick={onClick} className="cursor-pointer px-3 py-2.5 text-ink-muted">
        {row.created ?? "—"}
      </td>
      <td onClick={onClick} className="cursor-pointer px-3 py-2.5">
        <ProcessingBadge
          tags={row.lifecycle_tags}
          errorMessage={row.ai_error_message}
          inFlight={inFlight}
        />
      </td>
    </tr>
  );
}

const inputCls =
  "mt-1 block w-full rounded-md border border-hairline bg-canvas px-2 py-1.5 text-sm text-ink placeholder:text-ink-faint focus:border-accent focus:outline-none";

function Field({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <label className="block text-xs font-medium text-ink-muted">
      {label}
      {children}
    </label>
  );
}

function ZurPruefungTab() {
  const navigate = useNavigate();
  const list = useInboxList({ pageSize: 50, ordering: "-modified" });
  const bulkApprove = useBulkApprove();

  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [lastResult, setLastResult] = useState<{
    succeeded: number;
    failed: number;
  } | null>(null);

  const visibleIds = useMemo(
    () => list.data?.results.map((r) => r.id) ?? [],
    [list.data],
  );

  const effectiveSelected = useMemo(() => {
    if (!visibleIds.length) return selected;
    const visible = new Set(visibleIds);
    let pruned = false;
    const next = new Set<number>();
    selected.forEach((id) => {
      if (visible.has(id)) next.add(id);
      else pruned = true;
    });
    return pruned ? next : selected;
  }, [selected, visibleIds]);

  const selectedCount = effectiveSelected.size;
  const allSelected =
    visibleIds.length > 0 && visibleIds.every((id) => effectiveSelected.has(id));

  const toggleOne = (id: number) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const toggleAll = () => {
    if (allSelected) setSelected(new Set());
    else setSelected(new Set(visibleIds));
  };

  const onBulkApprove = async () => {
    const ids = Array.from(effectiveSelected);
    if (ids.length === 0) return;
    setLastResult(null);
    const res = await bulkApprove.mutateAsync(ids);
    setLastResult({ succeeded: res.succeeded.length, failed: res.failed.length });
    setSelected((prev) => {
      const next = new Set(prev);
      res.succeeded.forEach((id) => next.delete(id));
      return next;
    });
  };

  return (
    <main className="mx-auto w-full max-w-5xl flex-1 px-6 py-6">
      <div className="flex items-baseline justify-between">
        <div>
          <h1 className="text-lg font-semibold tracking-tight text-ink">
            Zur Prüfung
          </h1>
          <p className="mt-0.5 text-sm text-ink-muted">
            Dokumente warten auf Ihre Prüfung. Zuletzt geänderte zuerst.
          </p>
        </div>
        <span className="text-sm text-ink-subtle">
          {list.data ? `${list.data.total} offen` : "…"}
        </span>
      </div>

      {list.isError && (
        <p className="mt-4 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
          Konnte die Liste nicht laden.
        </p>
      )}

      {list.data && list.data.results.length === 0 && (
        <div className="mt-8 rounded-lg border border-dashed border-hairline bg-surface p-8 text-center text-sm text-ink-subtle">
          Keine offenen Dokumente.{" "}
          <Link to="/ask" className="font-medium text-ink underline">
            Suche stattdessen.
          </Link>
        </div>
      )}

      {list.data && list.data.results.length > 0 && (
        <>
          {selectedCount > 0 && (
            <div className="sticky top-0 z-10 mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-inverse/20 bg-inverse px-4 py-2 text-sm text-on-inverse">
              <span>
                {selectedCount}{" "}
                {selectedCount === 1
                  ? "Dokument ausgewählt"
                  : "Dokumente ausgewählt"}
              </span>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => setSelected(new Set())}
                  disabled={bulkApprove.isPending}
                  className="rounded-md border border-white/20 px-3 py-1 text-xs text-on-inverse/80 hover:bg-white/10 disabled:opacity-60"
                >
                  Auswahl aufheben
                </button>
                <button
                  type="button"
                  onClick={onBulkApprove}
                  disabled={bulkApprove.isPending}
                  className="rounded-md bg-surface px-3 py-1 text-xs font-medium text-ink hover:bg-canvas disabled:opacity-60"
                >
                  {bulkApprove.isPending
                    ? "Genehmige…"
                    : `${selectedCount} genehmigen`}
                </button>
              </div>
            </div>
          )}

          {lastResult && (
            <p
              className={`mt-3 rounded-lg border px-3 py-2 text-sm ${
                lastResult.failed
                  ? "border-amber-200 bg-amber-50 text-amber-800"
                  : "border-emerald-200 bg-emerald-50 text-emerald-800"
              }`}
            >
              {lastResult.succeeded} genehmigt
              {lastResult.failed
                ? ` · ${lastResult.failed} fehlgeschlagen`
                : ""}
              .
            </p>
          )}

          <div className="mt-4 rounded-lg border border-hairline bg-surface">
            <table className="w-full text-left text-sm">
              <thead className="border-b border-hairline text-xs uppercase tracking-wide text-ink-subtle">
                <tr>
                  <th className="w-8 px-3 py-2.5">
                    <input
                      type="checkbox"
                      aria-label="Alle auswählen"
                      checked={allSelected}
                      onChange={toggleAll}
                      className="h-4 w-4 cursor-pointer accent-ink"
                    />
                  </th>
                  <th className="px-3 py-2.5">Titel</th>
                  <th className="px-3 py-2.5">Typ</th>
                  <th className="px-3 py-2.5">Korrespondent</th>
                  <th className="px-3 py-2.5">Datum</th>
                  <th className="px-3 py-2.5 text-right">Konfidenz</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-hairline-soft">
                {list.data.results.map((row) => (
                  <ReviewRow
                    key={row.id}
                    row={row}
                    checked={effectiveSelected.has(row.id)}
                    onToggle={() => toggleOne(row.id)}
                    onOpen={() =>
                      navigate({
                        to: "/inbox/$id",
                        params: { id: String(row.id) },
                      })
                    }
                  />
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}
    </main>
  );
}

function ReviewRow({
  row,
  checked,
  onToggle,
  onOpen,
}: {
  row: InboxItem;
  checked: boolean;
  onToggle: () => void;
  onOpen: () => void;
}) {
  const flagCls = row.low_confidence ? "border-l-2 border-amber-400" : "";
  return (
    <tr className={`hover:bg-canvas ${flagCls}`}>
      <td className="w-8 px-3 py-2.5" onClick={(e) => e.stopPropagation()}>
        <input
          type="checkbox"
          aria-label={`${row.title} auswählen`}
          checked={checked}
          onChange={onToggle}
          className="h-4 w-4 cursor-pointer accent-ink"
        />
      </td>
      <td onClick={onOpen} className="cursor-pointer px-3 py-2.5 font-medium text-ink">
        {row.title}
      </td>
      <td onClick={onOpen} className="cursor-pointer px-3 py-2.5 text-ink-muted">
        {row.ai_document_type ?? "—"}
      </td>
      <td onClick={onOpen} className="cursor-pointer px-3 py-2.5 text-ink-muted">
        {row.ai_correspondent ?? "—"}
      </td>
      <td onClick={onOpen} className="cursor-pointer px-3 py-2.5 text-ink-muted">
        {row.ai_issue_date ?? row.created ?? "—"}
      </td>
      <td onClick={onOpen} className="cursor-pointer px-3 py-2.5 text-right text-ink-muted">
        {row.ai_confidence != null
          ? `${Math.round(row.ai_confidence * 100)}%`
          : "—"}
      </td>
    </tr>
  );
}
