// apps/web/src/routes/Trash.tsx
import { useState } from "react";

import { Nav } from "../components/Nav";
import {
  trashDaysRemaining,
  useDeleteForever,
  useEmptyTrash,
  useRestoreFromTrash,
  useTrashList,
  type TrashItem,
} from "../lib/trash";

export function Trash() {
  const list = useTrashList({ pageSize: 50 });
  const empty = useEmptyTrash();
  const [confirmingEmpty, setConfirmingEmpty] = useState(false);
  const [toast, setToast] = useState<string | null>(null);

  const total = list.data?.total ?? 0;
  const rows = list.data?.results ?? [];

  const onEmptyConfirm = async () => {
    try {
      const result = await empty.mutateAsync();
      setToast(`${result.emptied} Dokument(e) endgültig gelöscht`);
      window.setTimeout(() => setToast(null), 4000);
    } catch {
      setToast("Papierkorb konnte nicht geleert werden");
      window.setTimeout(() => setToast(null), 4000);
    } finally {
      setConfirmingEmpty(false);
    }
  };

  return (
    <div className="flex min-h-screen flex-col bg-canvas text-ink">
      <Nav active="trash" />
      <main className="mx-auto w-full max-w-6xl px-6 py-8">
        <header className="mb-6 flex items-end justify-between">
          <div>
            <h1 className="text-xl font-semibold">Papierkorb</h1>
            <p className="mt-1 text-sm text-ink-muted">
              Dokumente sind 30 Tage wiederherstellbar, dann werden sie
              automatisch endgültig gelöscht.
            </p>
          </div>
          {total > 0 && (
            <button
              onClick={() => setConfirmingEmpty(true)}
              disabled={empty.isPending}
              className="rounded-md border border-red-200 bg-white px-3 py-1.5 text-sm text-red-700 hover:bg-red-50 disabled:opacity-50"
            >
              Papierkorb leeren
            </button>
          )}
        </header>

        {list.isLoading && (
          <p className="text-sm text-ink-subtle">Lade Papierkorb…</p>
        )}

        {list.isError && (
          <p className="text-sm text-red-700">
            Papierkorb konnte nicht geladen werden:{" "}
            {list.error?.message ?? "Unbekannter Fehler"}
          </p>
        )}

        {!list.isLoading && !list.isError && rows.length === 0 && (
          <div className="rounded-md border border-hairline bg-surface p-8 text-center text-sm text-ink-muted">
            Papierkorb ist leer
          </div>
        )}

        {rows.length > 0 && (
          <ul className="divide-y divide-hairline rounded-md border border-hairline bg-surface">
            {rows.map((row) => (
              <TrashRow key={row.id} row={row} />
            ))}
          </ul>
        )}
      </main>

      {confirmingEmpty && (
        <ConfirmEmptyModal
          count={total}
          pending={empty.isPending}
          onCancel={() => setConfirmingEmpty(false)}
          onConfirm={onEmptyConfirm}
        />
      )}

      {toast && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 rounded-md bg-ink px-4 py-2 text-sm text-white shadow-lg">
          {toast}
        </div>
      )}
    </div>
  );
}

function TrashRow({ row }: { row: TrashItem }) {
  const restore = useRestoreFromTrash();
  const deleteForever = useDeleteForever();
  const [confirmingDelete, setConfirmingDelete] = useState(false);
  const daysLeft = trashDaysRemaining(row.deleted_at);
  const correspondent = row.correspondent ?? row.ai_correspondent ?? "—";
  const docType = row.document_type ?? row.ai_document_type ?? "—";

  const onRestore = async () => {
    try {
      await restore.mutateAsync(row.id);
    } catch {
      /* surface via the inline error below */
    }
  };

  const onDeleteForever = async () => {
    try {
      await deleteForever.mutateAsync(row.id);
    } catch {
      /* surface via the inline error below */
    } finally {
      setConfirmingDelete(false);
    }
  };

  const error =
    restore.error?.message ?? deleteForever.error?.message ?? null;

  return (
    <li className="flex flex-col gap-3 px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
      <div className="min-w-0 flex-1">
        <p className="truncate text-sm font-medium text-ink">{row.title}</p>
        <p className="mt-0.5 truncate text-xs text-ink-subtle">
          {correspondent} · {docType}
          {daysLeft !== null && (
            <span className="ml-2 text-ink-muted">noch {daysLeft} Tage</span>
          )}
        </p>
        {error && <p className="mt-1 text-xs text-red-700">{error}</p>}
      </div>
      <div className="flex items-center gap-2">
        <button
          onClick={onRestore}
          disabled={restore.isPending || deleteForever.isPending}
          className="rounded-md border border-hairline bg-white px-3 py-1 text-xs text-ink hover:bg-canvas disabled:opacity-50"
        >
          {restore.isPending ? "…" : "Wiederherstellen"}
        </button>
        {!confirmingDelete ? (
          <button
            onClick={() => setConfirmingDelete(true)}
            disabled={restore.isPending || deleteForever.isPending}
            className="rounded-md border border-red-200 bg-white px-3 py-1 text-xs text-red-700 hover:bg-red-50 disabled:opacity-50"
          >
            Endgültig löschen
          </button>
        ) : (
          <>
            <button
              onClick={() => setConfirmingDelete(false)}
              disabled={deleteForever.isPending}
              className="rounded-md border border-hairline bg-white px-3 py-1 text-xs text-ink-muted hover:bg-canvas disabled:opacity-50"
            >
              Abbrechen
            </button>
            <button
              onClick={onDeleteForever}
              disabled={deleteForever.isPending}
              className="rounded-md bg-red-600 px-3 py-1 text-xs font-medium text-white hover:bg-red-700 disabled:opacity-50"
            >
              {deleteForever.isPending ? "…" : "Ja, endgültig löschen"}
            </button>
          </>
        )}
      </div>
    </li>
  );
}

function ConfirmEmptyModal({
  count,
  pending,
  onCancel,
  onConfirm,
}: {
  count: number;
  pending: boolean;
  onCancel: () => void;
  onConfirm: () => void;
}) {
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4"
      role="dialog"
      aria-modal="true"
    >
      <div className="w-full max-w-md rounded-lg bg-surface p-6 shadow-2xl">
        <h2 className="text-base font-semibold text-ink">
          Papierkorb leeren?
        </h2>
        <p className="mt-2 text-sm text-ink-muted">
          {count === 1
            ? "1 Dokument wird endgültig gelöscht. Dies kann nicht rückgängig gemacht werden."
            : `${count} Dokumente werden endgültig gelöscht. Dies kann nicht rückgängig gemacht werden.`}
        </p>
        <div className="mt-5 flex items-center justify-end gap-2">
          <button
            onClick={onCancel}
            disabled={pending}
            className="rounded-md border border-hairline bg-white px-3 py-1.5 text-sm text-ink-muted hover:bg-canvas disabled:opacity-50"
          >
            Abbrechen
          </button>
          <button
            onClick={onConfirm}
            disabled={pending}
            className="rounded-md bg-red-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-red-700 disabled:opacity-50"
          >
            {pending ? "Lösche…" : "Ja, alle endgültig löschen"}
          </button>
        </div>
      </div>
    </div>
  );
}

// apps/web/app/pages/trash.vue
<script setup lang="ts">
definePageMeta({ middleware: "auth" });

const list = useTrashList();
const restore = useRestore();
const deleteForever = useDeleteForever();
const emptyTrash = useEmptyTrash();

const confirmingDelete = ref<number | null>(null);
const confirmingEmpty = ref(false);

const rows = computed<readonly TrashItem[]>(() => list.data.value?.results ?? []);
const total = computed(() => list.data.value?.total ?? 0);

const errorText = computed(() => {
  if (restore.isError.value) return detailFrom(restore.error.value, "Wiederherstellen fehlgeschlagen.");
  if (deleteForever.isError.value) return detailFrom(deleteForever.error.value, "Löschen fehlgeschlagen.");
  if (emptyTrash.isError.value) return detailFrom(emptyTrash.error.value, "Leeren fehlgeschlagen.");
  return null;
});

function remaining(item: TrashItem): string {
  const days = daysLeft(item.deleted_at);
  return days === null ? "—" : `noch ${days} Tage`;
}

async function onRestore(id: number): Promise<void> {
  await restore.mutateAsync(id).catch(() => undefined);
}

async function onDelete(id: number): Promise<void> {
  if (confirmingDelete.value !== id) {
    confirmingDelete.value = id;
    return;
  }
  confirmingDelete.value = null;
  await deleteForever.mutateAsync(id).catch(() => undefined);
}

async function onEmpty(): Promise<void> {
  if (!confirmingEmpty.value) {
    confirmingEmpty.value = true;
    return;
  }
  confirmingEmpty.value = false;
  await emptyTrash.mutateAsync().catch(() => undefined);
}
</script>

<template>
  <div class="mx-auto w-full max-w-4xl px-4 py-8 sm:px-6">
    <div class="flex items-baseline justify-between gap-3">
      <div>
        <h1 class="text-lg font-semibold tracking-tight text-ink">Papierkorb</h1>
        <p class="mt-0.5 text-xs text-ink-muted">Gelöschte Dokumente bleiben 30 Tage wiederherstellbar.</p>
      </div>
      <button
        v-if="rows.length > 0"
        type="button"
        :disabled="emptyTrash.isPending.value"
        data-testid="empty-trash"
        class="rounded-lg border px-3 py-1.5 text-xs font-medium disabled:opacity-50"
        :class="confirmingEmpty ? 'border-red-300 text-red-700' : 'border-hairline text-ink'"
        @click="onEmpty"
      >
        {{
          emptyTrash.isPending.value
            ? "leere…"
            : confirmingEmpty
              ? "Wirklich? Erneut klicken"
              : "Papierkorb leeren"
        }}
      </button>
    </div>

    <p v-if="errorText" class="mt-4 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
      {{ errorText }}
    </p>

    <p v-if="list.isPending.value" class="mt-6 text-xs text-ink-subtle">Lade Papierkorb…</p>
    <p
      v-else-if="rows.length === 0"
      class="mt-6 rounded-lg border border-dashed border-hairline bg-surface p-8 text-center text-sm text-ink-subtle"
    >
      Der Papierkorb ist leer.
    </p>
    <template v-else>
      <p class="mt-4 text-xs text-ink-subtle">{{ total }} Dokument(e)</p>
      <ul class="mt-2 flex flex-col gap-2">
        <li
          v-for="row in rows"
          :key="row.id"
          class="flex flex-wrap items-center gap-3 rounded-lg border border-hairline bg-surface p-3"
        >
          <div class="min-w-0 flex-1">
            <p class="truncate text-sm font-medium text-ink">{{ row.title }}</p>
            <p class="mt-0.5 text-xs text-ink-muted">
              {{ row.document_type ?? row.ai_document_type ?? "—" }} ·
              {{ row.correspondent ?? row.ai_correspondent ?? "—" }} · {{ remaining(row) }}
            </p>
          </div>
          <button
            type="button"
            :disabled="restore.isPending.value"
            :data-testid="`restore-${row.id}`"
            class="rounded-lg border border-hairline px-3 py-1.5 text-xs font-medium text-ink hover:bg-canvas disabled:opacity-50"
            @click="onRestore(row.id)"
          >
            Wiederherstellen
          </button>
          <button
            type="button"
            :disabled="deleteForever.isPending.value"
            :data-testid="`delete-${row.id}`"
            class="rounded-lg border px-3 py-1.5 text-xs font-medium disabled:opacity-50"
            :class="confirmingDelete === row.id ? 'border-red-300 text-red-700' : 'border-hairline text-ink'"
            @click="onDelete(row.id)"
          >
            {{ confirmingDelete === row.id ? "Wirklich?" : "Endgültig löschen" }}
          </button>
        </li>
      </ul>
    </template>
  </div>
</template>
